# Related scripts
train_script_name: common
module_script_name: ASID
class_name: ASID
# Model Configuration
feature_num: 48
module_params:
  upsampling: 8
  res_num: 3
  block_num: 1
  bias: True
  block_script_name: IDSA
  block_class_name: IDSA_Block2
  window_size: 8
  pe: True
  ffn_bias: True

# Training information
total_epoch: 2

# Dataset
dataloader: DIV2K_memory
dataset_name: DIV2K 
batch_size: 4
random_seed: 1234
dataset_params:
  lr_patch_size: 32
  degradation: bicubic
  image_scale: 8
  subffix: png
  dataloader_workers: 2
  dataset_enlarge: 2
  color_jitter: False
  color_config:
    brightness: 0.02
    contrast:   0.02
    saturation: 0.02
    hue:        0.02
  enable_reshuffle: False

eval_dataloader: memory
eval_dataset_name: Set5
eval_batch_size: 1

# Optimizer
lr_decay: 0.5
lr_decay_step: [1, 2]
lr_decay_enable: True
optim_type: AdamW
optim_config:
  lr: !!float 5e-4
  betas: [0.9, 0.999]
  weight_decay: !!float 1e-4

# Losses
l1_weight: 30.0
perceptual:
  layer_weights:
    'conv5_4': 1  # before relu
  vgg_type: vgg19
  use_input_norm: true
  perceptual_weight: 1.0
  criterion: l1

# Log 
log_step: 2
sample_step: 5
model_save_epoch: 1
use_tensorboard: True
checkpoint_names:
  generator_name: ASID
